DROP TABLE IF EXISTS persona;

CREATE TABLE persona (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  nombre VARCHAR(250) NOT NULL,
  apellido VARCHAR(250) NOT NULL,
  direccion VARCHAR(250) DEFAULT NULL,
  telefono VARCHAR(250) DEFAULT NULL
);